### ISSUE TITLE
API returned values

### ISSUE THREAD

**Issue by AbbyArsenic** [Zeeroh0/NexGen-Calc#14]
On the flight plan page, if KIWA is entered as the airport, the temperature value returns blank and placeholder text "please enter an airport code above" is displayed. If another airport (ex. kphx) is entered, temperature displays a numeric value.

**Comment by Zeeroh0** [comment]
Bug was due to the response object having inconsistent values.  Sometimes, it seems, some data is just not included.  

Rebuilt the capture method for the temp to be more conditional
