### ISSUE TITLE
Update layouts 

### ISSUE THREAD

**Issue by Zeeroh0** [Zeeroh0/NexGen-Calc#8]
Need to update the layouts on a few pages to better reflect what we need to get/display

For instance, update: 
- Flight Plan page
-- Need to ask for take off and landing Airport, Weight, Headwind

- Take Off/Landing Data pages
-- Make this one page w two columns 
-- Have this display the calculated values for each column (take off and landing)

**Comment by Zeeroh0** [comment]
TOLD Review page contents: 

- Take Off 
  - Pressure Altitude
  - Density Altitude
  - Take Off Roll
  - Lift Off Speed 
  - Lift Off Speed (over a 50 ft barrier)
  - Accelerate Stop
  - Take off Distance (over a 50 ft barrier)
  - Climb Rate 
- Landing 
  - Pressure Altitude
  - Density Altitude
  - Landing Distance 
  - Landing Distance (over a 50 ft barrier)

**Comment by AbbyArsenic** [comment]
Layouts for TOLD review and TOLD Card are basically done. Still need info fed to them from user input on previous page.
